### ISSUE TITLE
Client pushing orb not synchronized with host 

### ISSUE THREAD

**Issue by Astr042** [thm-mni-ii/SWT-P_SS20_Overcooked#111]
When the client pushes orbs that are on the ground, they are not moving correctly on the server.
Video of the bug in the youtube video below

https://www.youtube.com/watch?v=2PTLw-TRv64

**Comment by Astr042** [comment]
Thank you @JoeGre666 for finding that bug

**Comment by pantAlex** [comment]
Yes, @JoeGre666 
Thanks!!

**Comment by JoeGre666** [comment]
> Thank you @JoeGre666 for finding that bug

That's my f***ing job!
