### ISSUE TITLE
Mockup-Bilder

### ISSUE THREAD

**Issue by saltonyou** [thm-mni-ii/SWT-P_SS20_Overcooked#2]
![Level1](https://user-images.githubusercontent.com/63291288/81294225-defac480-906e-11ea-8747-a6e45a2eed01.jpg)
![Level2](https://user-images.githubusercontent.com/63291288/81294226-defac480-906e-11ea-8b16-4949b01e822f.jpg)
![Level3](https://user-images.githubusercontent.com/63291288/81294219-ddc99780-906e-11ea-8efd-2ac5449e390e.jpg)
![rezepte](https://user-images.githubusercontent.com/63291288/81294224-defac480-906e-11ea-85ef-821391491f66.jpg)

**Comment by saltonyou** [comment]
![Level_4](https://user-images.githubusercontent.com/63291288/81931439-6b1a6800-95ea-11ea-9ad9-19e27605b8b9.jpg)

**Comment by Astr042** [comment]
Those are already in the wiki
