### ISSUE TITLE
InGame-Bilder

### ISSUE THREAD

**Issue by saltonyou** [thm-mni-ii/SWT-P_SS20_Overcooked#3]
![ErsterServerTest](https://user-images.githubusercontent.com/63291288/81295247-685ec680-9070-11ea-96e4-39a6c3be5403.png)

**Comment by saltonyou** [comment]
![behaelter](https://user-images.githubusercontent.com/63291288/83116757-87c79d00-a0cc-11ea-8ba5-776c779e620e.png)

**Comment by saltonyou** [comment]
![prototype](https://user-images.githubusercontent.com/63291288/83127264-3f16e080-a0da-11ea-8a74-11baa8c07152.PNG)

**Comment by saltonyou** [comment]
![yeeet](https://user-images.githubusercontent.com/63291288/84998474-2d13e500-b150-11ea-9ce1-49b2ba5f9450.gif)

**Comment by saltonyou** [comment]
![yeeet](https://user-images.githubusercontent.com/63291288/85550457-466dd300-b621-11ea-9260-bb80476fee39.gif)

**Comment by saltonyou** [comment]
![yeeet2](https://user-images.githubusercontent.com/63291288/85551175-078c4d00-b622-11ea-9ca1-2f756e755e04.gif)

**Comment by DominikH1995** [comment]
https://cdn.discordapp.com/attachments/702917350940475392/725657850004766730/kupferoxid.png

**Comment by saltonyou** [comment]
![image](https://user-images.githubusercontent.com/63291288/86236473-6d388600-bb9a-11ea-932c-4140d768c310.png)

**Comment by saltonyou** [comment]
![newLevelDesign](https://user-images.githubusercontent.com/63291288/86256305-77697d00-bbb8-11ea-9b5b-9e981931789e.png)
**_noch nicht im Wiki eingebaut_**

**Comment by saltonyou** [comment]
![image](https://user-images.githubusercontent.com/63291288/86256422-99fb9600-bbb8-11ea-849c-c0b64af5780d.png)
_**auch noch nicht verwendet**_

**Comment by saltonyou** [comment]
![scoreboardv1](https://user-images.githubusercontent.com/63291288/86926586-8b6e2b00-c132-11ea-9297-e04bdf440a87.png)

**Comment by saltonyou** [comment]
![LevelScreenFinished](https://user-images.githubusercontent.com/63291288/87606627-be4c8c00-c6fb-11ea-88bd-d15fe153805b.png)

**Comment by saltonyou** [comment]
![New Input System](https://user-images.githubusercontent.com/63291288/91614140-44a5f000-e981-11ea-9847-a2a7ff537f52.png)

**Comment by DominikH1995** [comment]
<img width="170" alt="Destillationsgerät" src="https://user-images.githubusercontent.com/63615714/91635448-e9174900-e9f8-11ea-9db2-397b56ba76aa.PNG">

**Comment by DominikH1995** [comment]
<img width="132" alt="Bunsenbrenner" src="https://user-images.githubusercontent.com/63615714/91635481-27146d00-e9f9-11ea-857a-6b6dfdf16a01.PNG">

**Comment by DominikH1995** [comment]
<img width="117" alt="Essigsäure-Gerät" src="https://user-images.githubusercontent.com/63615714/91635501-47442c00-e9f9-11ea-8100-e26df66a7c0f.PNG">

**Comment by DominikH1995** [comment]
<img width="229" alt="Elektrolyse-Gerät" src="https://user-images.githubusercontent.com/63615714/91635513-65119100-e9f9-11ea-9490-8147c33b9a3d.PNG">

**Comment by DominikH1995** [comment]
<img width="92" alt="Wasserstoffgenerator" src="https://user-images.githubusercontent.com/63615714/91635528-870b1380-e9f9-11ea-894a-85efcdc898ba.PNG">

**Comment by DominikH1995** [comment]
<img width="116" alt="Urinsäure-Gerät" src="https://user-images.githubusercontent.com/63615714/91635537-95f1c600-e9f9-11ea-9b4b-a32c75fc0f08.PNG">

**Comment by saltonyou** [comment]
![image](https://user-images.githubusercontent.com/63291288/91676006-aa8ba680-eb3e-11ea-9300-deb4d6c23fbb.png)

**Comment by DominikH1995** [comment]
<img width="736" alt="LevelUI und TutorialUI" src="https://user-images.githubusercontent.com/63615714/91664959-c6695b00-eaf2-11ea-837d-6bc1a06ad302.PNG">

**Comment by DominikH1995** [comment]
<img width="733" alt="LevelFinishedUI" src="https://user-images.githubusercontent.com/63615714/91665030-1fd18a00-eaf3-11ea-8b9e-04ee3ae7dcef.PNG">

**Comment by DominikH1995** [comment]
<img width="734" alt="Level 0" src="https://user-images.githubusercontent.com/63615714/91665769-5bbb1e00-eaf8-11ea-8b0f-fe8e5e483920.PNG">

**Comment by DominikH1995** [comment]
<img width="733" alt="Level 1" src="https://user-images.githubusercontent.com/63615714/91665796-7e4d3700-eaf8-11ea-9898-858c63c682f8.PNG">

**Comment by DominikH1995** [comment]
<img width="731" alt="Level 2" src="https://user-images.githubusercontent.com/63615714/91665826-ab014e80-eaf8-11ea-8ba5-ea5d4c8f98ec.PNG">

**Comment by Astr042** [comment]
pictures are in the wiki
