### ISSUE TITLE
UML-Diagramm

### ISSUE THREAD

**Issue by saltonyou** [thm-mni-ii/SWT-P_SS20_Overcooked#4]
v1 
![Use_Case_diagram_Underconnected](https://user-images.githubusercontent.com/63291288/81931883-13c8c780-95eb-11ea-9022-77f1cdf40da5.png)

**Comment by DominikH1995** [comment]
![Use_Case_diagram_Underconnected_ohne_Legende](https://user-images.githubusercontent.com/63615714/81935025-3c06f500-95f0-11ea-9dd4-aa00294af92c.png)

**Comment by saltonyou** [comment]
![image](https://user-images.githubusercontent.com/63291288/83120717-b136f780-a0d1-11ea-978c-d66afc3cc04a.png)

**Comment by saltonyou** [comment]
![image](https://user-images.githubusercontent.com/63291288/84687303-ce771d00-af3d-11ea-84b7-97f803b89fc6.png)

**Comment by Astr042** [comment]
can be found in wiki
