### ISSUE TITLE
Level finished screen [8🍪]

### ISSUE THREAD

**Issue by pantAlex** [thm-mni-ii/SWT-P_SS20_Overcooked#53]
Show a summary screen at the end of each level.

It shows information such as:
- Score
- Completed recipes
- Rating?

**Comment by saltonyou** [comment]
What font does the framework use?

**Comment by saltonyou** [comment]
Is there also a maximum number of letters for a user name? (see here: first user name _xXx-No0o0o0Sc0p3zzzxXx_ https://github.com/thm-mni-ii/SWT-P_SS20_Overcooked/wiki/Punktesystem )

**Comment by pantAlex** [comment]
.̴̨͎͎͓̦͕̮͒̈̾̂́̍̍͜͠:̴̺̪̞̞͎̘̃͌͒̀̑.̷̡̛̛̹̺̱̖̙͓̃̔͑̀̄͘͝͝:̷͓͐̿̚.̶̧̪̬̭͇͎̝̝̼͊:̷̧͙͕̬̪͎͔̲̣̥̆̈́̈́̒́̐͛͂̕.̶͇̙̠̳͎͔̽̅̇̃̍̃́̚͠͝:̵̮̍̐̋.̵̪̾:̶̨̻͎̘͔̟̙̙̂̋̌̈́̓̉̚͜͝.̵̡̪̩̙̤̥̘͓̠̓̑͛̄̒͌̅͆͠ͅ:̸͖̖̅̄͌̐͜͝͠͝.̵͕̱̣̥͎̀́̌̄ͅͅ:̸̲͎͇̳̩͙̈́͛͑͗̉̉̉̃̓̕ͅͅ.̶̧͖̫͋͒͒̊̆̉͗̚̕͜͝ͅ:̷͕͎̃̒̽̍̈́̄͗́.̵̨̮̬̜̙̥͔̦̏͆̓̈͒̅̽̀͜͝:̸̦̬̼̮̳̟̯͇̘̐̏͝
