### ISSUE TITLE
Create proper icons and descriptions for matters

### ISSUE THREAD

**Issue by pantAlex** [thm-mni-ii/SWT-P_SS20_Overcooked#89]
Right now some elements and compounds do not have their own icons.
E.g.: *Nitrogen* has no icon at all, *Ethane* and *Methane* are displayed as CO2, *Methanol* is displayed as C, etc.
Most matter elements still have a placeholder description.

Make sure that each element has its own icon, the correct formula and a proper description.

**Comment by JoeGre666** [comment]
- [x] still need to do descriptions

**Comment by JoeGre666** [comment]
Since we don't really display them ingame, it's not as important and most matters have a description anyway.
Sprites and textures were already updated, too.
