### ISSUE TITLE
Complete finish screen [5🍪]

### ISSUE THREAD

**Issue by JoeGre666** [thm-mni-ii/SWT-P_SS20_Overcooked#95]
- [x] We still need to add the "Exit"-Button functionality. -> moved to another issue (#136 )
 - [x] Additionally we need to test "Next Level"-Button some more, too.

**Comment by Astr042** [comment]
"next level" needs testing with additional levels and exit button ist currently not working.
New level need to be ready in order to be tested

**Comment by JoeGre666** [comment]
Closed this and created a new issues just for the exit button because it's framework related. "Next level"-Button works tho!
See #136 for further development.
